### ISSUE TITLE
Use MTGJSON?

### ISSUE THREAD

**Issue by multimeric** [ruler501/magic-card-parser#4]
I'm interesting in using and helping with this module. However, I've found installation to be quite complex because of the CubeCobra submodule thing going on (truth be told I don't really know what CubeCobra is). Might it be possible to simplify the testing/assessment of the parser by simply pulling down an MTGJSON file, and running over that? Is there a good reason to depend on CubeCobra?

Sidenote, the instructions as they are tell you to use `npm setup`, but I believe it's supposed to be `npm run setup`.

**Comment by danzel** [comment]
I have a PR for using scryfall json in #2 :+1:

**Comment by multimeric** [comment]
Ah, that seems good. I have no particular opinion on if MTGJSON or Scryfall is better (I think one is derived from the other?) so I'm happy to just defer to your PR. Nice work!
